### ISSUE TITLE
RowPairCalculator.damage_tp_fn_fp is not correctly calculated when a damage type is missing.

### ISSUE THREAD

**Issue by xvr-hlt** [DIUx-xView/xview2-scoring#1]
False positives are not correctly calculated for damage classes that do not occur in a given target.

```py
pred_d = np.array([[2,2], [2,2]])
targ_d = np.array([[0,0],[0,0]])
RowPairCalculator.damage_tp_fn_fp(pred_d, targ_d, 2) # expected: 0, 0, 4
>>> [None, None, None]
```
The problematic lines of code in RowPairCalculator.damage_tp_fn_fp are:

```
    if i in np.unique(targ_d): return list(cls.compute_tp_fn_fp(pred_d, targ_d, i))
    else: return [None, None, None]
``` 

because although a damage class not being in a target guarantees that there won't be any true positives or false negatives, the predicted map can still have false positives. This means certain errors aren't penalised and propagates through to the final metrics.

**Comment by NathanYee** [comment]
Thank you for pointing this out. I have submitted a [pull request](#2) that should fix this issue.
